### ISSUE TITLE
No sideline being displayed for flycheck errors

### ISSUE THREAD

**Issue by mplanchard** [emacs-sideline/sideline-flycheck#10]
I'm trying to use `sideline-flycheck` for janet files via [sogaiu/flycheck-janet](https://github.com/sogaiu/flycheck-janet).

Looking at the following file:

```janet
(foo "hello")
```

Flycheck shows errors appropriately, via `flycheck-list-errors`:

```
 day-01.janet     2   1 error           compile error: unknown symbol foo (janet-janet)
```

The error shows up in the echo area, but it does not show up in the sideline.

My config is (using elpaca):

```elisp
(use-package sideline :ensure t
  :hook ((flymake-mode . sideline-mode)
         (flycheck-mode . sideline-mode))
  :init
  (setq sideline-backends-right '(sideline-flycheck sideline-flymake)))

(use-package sideline-flycheck :ensure t
  :hook (flycheck-mode . sideline-flycheck-setup))
(use-package sideline-flymake :ensure t)
```

Potentially relevant variables:

```lisp
(sideline-mode t)
(flycheck-mode t)
(flycheck-mode-hook (sideline-flycheck-setup sideline-mode flycheck-mode-set-explicitly)
(sideline-backends-right (sideline-flycheck sideline-flymake))
 ```

I'm not getting anything at all in the sideline, and given that there don't seem to be any errors, I'm not really sure how to debug this.

**Comment by jcs090218** [comment]
One possible problem is that the error message is too long, so sideline omitted it. Maybe try `(setq sideline-truncate t).` 🤔

**Comment by mplanchard** [comment]
Yep, that did it! It's weird, because it's a pretty short message, just `compile error: unknown symbol foo`, so I didn't even think to try truncating.

Thank you for the quick reply!

**Comment by jcs090218** [comment]
> Yep, that did it! It's weird, because it's a pretty short message, just compile error: unknown symbol foo, so I didn't even think to try truncating.

How wide is your window? Maybe it's too narrow? 🤔 Or else it would be a bug (hope not). 😅

**Comment by mplanchard** [comment]
It doesn't seem to show up regardless of the size of the window: `(window-total-width)` returns 225 columns for the window at full screen size. The `sideline-truncate-suffix` (`...`) also doesn't show up in the message when it is showing up after enabling `sideline-truncate`. 

Happy to help debugging anything where it would be useful.

Versions are:

```
sideline: installed version: 0.2.0 0307db5
sideline-flycheck: installed version: 0.1.0 1cc46a2
flycheck: installed version: 35.0-snapshot 5217e0e0
```

**Comment by jcs090218** [comment]
It seems like you are using an older version of sideline. 🤔 Maybe try upgrade to the latest version. :)

**Comment by mplanchard** [comment]
Yep, that did it, thank you! Turned out I had old melpa definitions, possibly due to progfolio/elpaca#385
