### ISSUE TITLE
How to trigger display outside highlighted region on the same line like `lsp-ui`?

### ISSUE THREAD

**Issue by failable** [emacs-sideline/sideline-flycheck#5]
It's a bit inconvenient that one has to move the point to the highlighted region to see the sideline message.

lsp-ui
<img width="965" alt="Screenshot 2023-11-19 at 15 24 43" src="https://github.com/emacs-sideline/sideline-flycheck/assets/5475262/14c10524-5aaf-455b-89af-27ebf7b90ba5">

sideline
<img width="968" alt="Screenshot 2023-11-19 at 15 26 25" src="https://github.com/emacs-sideline/sideline-flycheck/assets/5475262/10c308da-dda3-4ad1-83a2-f0d92331f1ba">

**Comment by jcs090218** [comment]
Yeah, this is currently not possible. I will implement this when I have more time!

Feel free to open PRs for this feature! :)

**Comment by jcs090218** [comment]
You can now achieve this by:

```elisp
(setq sideline-flycheck-display-mode 'line)
```
